version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopass
    ports:
      - "3307:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: todo-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  todo-mysql-data:
